import { FastifyReply, FastifyRequest } from "fastify";
import { wiow, nws } from "../..";

const nwsMovies = [
  "‎The Chronicles of Riddick",
  "Zombieland",
  "Zodiac",
  "Zero Dark Thirty",
  "Zathura: A Space Adventure",
  "Young Guns",
  "You Were Never Really Here",
  "You Only Live Twice",
  "You Can't Watch This",
  "Yesterday",
  "Yellowstone",
  "XXX",
  "X-Men: The Animated Series",
  "Wrath of the Titans",
  "Wrath of Man",
  "Woodlawn",
  "With Honors",
  "Wire Room",
  "Wings",
  "Windtalkers",
  "Willy Wonka & The Chocolate Factory",
  "Willow (1988)",
  "WILL TRENT (IS WOKE!)",
  "Wilfred",
  "Why The Nativity?",
  "White Noise",
  "White House Plumbers",
  "White Christmas",
  "Whiplash",
  "While You Were Sleeping",
  "Where The Red Fern Grows",
  "Whatever - Dating Talk",
  "What We Do in the Shadows",
  "What Is A Woman?",
  "What Dreams May Come",
  "What About Bob?",
  "Westworld (IS WOKE!)",
  "Welcome to Wrexham",
  "Weird: The Al Yankovic Story",
  "Weird Science",
  "wecrashed",
  "We Were Soldiers",
  "We Are Marshall",
  "Wayne's World",
  "Watchmen",
  "Warrior",
  "WarGames (War Games)",
  "Warcraft",
  "War Room With Steve Bannon",
  "War Room",
  "War of The Worlds (2005)",
  "War Machine",
  "War Horse",
  "War for the Planet of the Apes",
  "War Dogs",
  "Walt's Disenchanted Kingdom",
  "Walk The Line",
  "Waldo on Weed",
  "Wakfu",
  "Wag The Dog",
  "Waco: The Aftermath",
  "Waco",
  "Vlog Creations (Ross Creations)",
  "Virgin River",
  "Vince Dao",
  "Vikings (IS WOKE!)",
  "Video Games: The Movie",
  "Vice Principals",
  "Verdict with Ted Cruz",
  "VENGEANCE",
  "VeggieTales: The Toy That Saved Christmas",
  "VeggieTales in the House",
  "Veggie Tales: Where's God When I'm S-Scared?",
  "Veep",
  "Varsity Blues",
  "Valkyrie",
  "Utopia (2020)",
  "Upside Down",
  "Upload (IS WOKE!)",
  "Upgrade",
  "Up",
  "Unwoke Inc.",
  "Unstoppable",
  "Unstable",
  "United 93",
  "Unholy Brotherhood of The Electric Church (UBEC)",
  "Unforgiven",
  "Unearthed",
  "Underworld Rise of the Lycans",
  "Underworld Evolution",
  "Underworld",
  "Undercover Underage",
  "Undercover Billionaire",
  "Under the Silver Lake",
  "Under the Banner of Heaven",
  "Under Siege",
  "Uncle Tom: Part II",
  "Uncle Tom",
  "Uncle Buck",
  "Uncharted 4: A Thief's End",
  "Uncharted",
  "Unbreakable Kimmy Schmidt",
  "Unapologetic with Amala",
  "U-571",
  "TÁR (IS WOKE!)",
  "Two and a Half Men (IS WOKE!)",
  "Twelve O'Clock High",
  "TURN: Washington's Spies",
  "Turbo Kid",
  "Tulsa King",
  "Tucker: The Man and His Dream",
  "Tucker On Twitter",
  "Tucker & Dale vs Evil",
  "Trying",
  "Trump Card",
  "True Lies",
  "True Grit",
  "True Detective",
  "Troy",
  "Tropic Thunder",
  "Tron",
  "Triggered",
  "Tribal People Try",
  "Treason",
  "Transfusion",
  "Transformers: Revenge of the Fallen",
  "Transformers: Dark of the Moon",
  "Transformers: Age of Extinction",
  "Transformers",
  "Training Day",
  "Traffic",
  "Touching the Void",
  "Total Recall (1990)",
  "Tora! Tora! Tora!",
  "Top Gun: Maverick",
  "Top Gear",
  "Top Boy",
  "Too Old to Die Young",
  "Tony Hawk: Until the Wheels Fall Off",
  "Tomorrow Never Dies",
  "Tommy Boy",
  "Tombstone",
  "Tom Clancy's Jack Ryan (IS WOKE!)",
  "Tolkien",
  "Tokyo Vice",
  "To Leslie",
  "To Die For",
  "To Catch A Killer (IS WOKE!)",
  "Titanic",
  "Tin Can",
  "Timecop",
  "Time Trap",
  "Time After Time (1979)",
  "Timcast IRL",
  "Timcast",
  "Tim Hawkins",
  "Tim Dillon",
  "Ticket to Paradise",
  "Thundercats",
  "Thunderball",
  "Three Kings",
  "Three Amigos!",
  "This Past Weekend With Theo Von",
  "This Is Going to Hurt",
  "This Fool (IS WOKE!)",
  "Thirteen Lives",
  "They Live",
  "There Will Be Blood",
  "Therapy Gecko",
  "TheFlyPaperPodcast",
  "The X-Files",
  "The Wrestler",
  "The World Is Not Enough",
  "The Wonder Years (1988)",
  "The Woman In The Window",
  "The Wolf of Wall Street",
  "The Wizard of Oz (1939)",
  "The Wire",
  "The Wingfeather Saga",
  "The Wind Rises",
  "The Wicker Man (1975)",
  "The Whale (IS WOKE!)",
  "The Wedding Singer",
  "The Way I Heard It with Mike Rowe",
  "The Way Back (2020)",
  "The Way Back (2010)",
  "The Waterboy",
  "The Warriors",
  "The War With Grandpa",
  "The Wandering Earth 2",
  "The Waltons",
  "The Wake Up Call With Josh Denny",
  "The Victor Davis Hanson Show",
  "The Venture Bros.",
  "The Vampire Diaries",
  "The Unbearable Weight of Massive Talent",
  "The Two Towers",
  "The Twilight Zone (1959)",
  "The Tudors",
  "The Truman Show",
  "The Trip",
  "The Tree Of Life",
  "The Transformers: The Movie",
  "The Transformers",
  "The Town",
  "The Tomorrow War",
  "The Tim Dillon Show",
  "The Three Musketeers (2011)",
  "The Three Musketeers (1993)",
  "The Three Body Problem",
  "The Third Day",
  "The Thing About Pam",
  "The Thing (1982)",
  "The Thin Red Line",
  "The Thaw",
  "The Terminator",
  "The Terminal List",
  "The Terminal",
  "The Ten Commandments",
  "The Tank",
  "The Tailor of Panama",
  "The Swamp",
  "The Super Mario Bros. Movie",
  "The Sum of All Fears",
  "The Subtle Art of Not Giving a #@%!",
  "The Star of Bethlehem",
  "The Stand at Paxton County",
  "The Staircase",
  "The Spy Who Loved Me",
  "The Spy",
  "The Spiked Vidcast",
  "The Spiked Podcast",
  "The Sound of Music",
  "The Sorcerer's Apprentice",
  "The Sopranos",
  "The Sons of Katie Elder",
  "The Smurfs",
  "The Sinner (IS WOKE)",
  "The Simpsons",
  "The Silence of the Lambs",
  "The Shrink Next Door",
  "The Shining",
  "The Shield",
  "The Shawshank Redemption",
  "The Shallows",
  "The Shadow State",
  "The Shadow Riders",
  "The Shack",
  "The Searchers",
  "The Scorpion King",
  "The Santa Clause",
  "The Sandlot",
  "The Sacketts",
  "The Running Man",
  "The Rundown",
  "The Rubin Report",
  "The Rockford Files",
  "The Road",
  "The Rise of Jordan Peterson",
  "The Ringer",
  "The Ring",
  "The Right Show With K-Von",
  "The Rider",
  "The Ride (1997)",
  "The Ride",
  "The Ricky Gervais Show",
  "The Returned",
  "The Return Of The King",
  "The Reluctant Traveler with Eugene Levy",
  "The Red Pill",
  "The Recruit (2022)",
  "THE RECKONING: Biden Crime Family​",
  "The Real Story of January 6",
  "The Real Anthony Fauci The Movie",
  "The Ranger, the Cook and a Hole in the Sky",
  "The Ranch (IS WOKE!)",
  "The Queen of Katwe",
  "The Pursuit of Happyness",
  "The Proposal",
  "The Program (2015)",
  "The Professor and the Madman",
  "The Prisoner (1968)",
  "The Princess Bride",
  "The Preacher's Wife",
  "The Poseidon Adventure (1972)",
  "The Plot Against the President",
  "The Platform",
  "The Place Beyond the Pines",
  "The Pixar Story",
  "The Pirates Who Don't Do Anything: A VeggieTales Movie",
  "The Physician",
  "The Phoenix Tapes '97",
  "The Phenomenon",
  "The Pez Outlaw",
  "The Peripheral (IS WOKE!)",
  "The Peanut Butter Falcon",
  "The Patriot",
  "The Patient",
  "The Passion Of The Christ",
  "The Parent Trap (1998)",
  "The Parent Trap (1961)",
  "The Pale Blue Eye",
  "The Pagemaster",
  "The Pacific",
  "The Outsiders",
  "The Outlaws (IS WOKE!)",
  "The Outlaw Josey Wales",
  "The Outlast Trials",
  "The Outfit",
  "The Others",
  "The Order of Rights",
  "The Order Of Rights",
  "The Old Way",
  "The Old Man",
  "The Office",
  "The Offer",
  "The Northman",
  "The North Water",
  "The Nightmare Before Christmas",
  "The Nightly Nuge",
  "The Night Manager",
  "The Night Agent",
  "The Next Three Days",
  "The Newsroom",
  "The Neverending Story",
  "The Negotiator",
  "The Mummy (1999)",
  "The Mule",
  "The Mountain Minor",
  "The Mother",
  "The Mosquito Coast (1986)",
  "The Moaning of Life",
  "The Mighty Ducks",
  "The Middle",
  "The Michael Savage Show",
  "The Michael Knowles Show",
  "The Mentalist (IS WOKE!)",
  "The Maze Runner",
  "The Matt Walsh Show",
  "The Matt Kim Show",
  "The Matador (2005)",
  "The Mask",
  "The Martian",
  "The Marksman",
  "The Mark Levin Show",
  "The Mandalorian",
  "The Man With the Golden Gun",
  "The Man Who Knew Infinity",
  "The Man in the Iron Mask",
  "The Man in the High Castle (IS WOKE!)",
  "The Man From Snowy River II",
  "The Man From Snowy River",
  "The Magnificent Seven",
  "The Machinist",
  "The Machine",
  "The Lost Boys (1987)",
  "The Looming Tower",
  "The Longest Day",
  "The Locksmith (2023)",
  "The Living Daylights",
  "The Lives Of Others",
  "The Little Rascals (1929)",
  "The Lion King (2019)",
  "The Line",
  "The Legend of Zelda: Tears of the Kingdom",
  "The Legend of the 81-Point Game",
  "The Legend of Korra (IS WOKE!)",
  "The Leftovers",
  "The League of Extraordinary Gentlemen",
  "The Lazarus Project",
  "The Last Thing He Told Me",
  "The Last Samurai",
  "The Last of the Mohicans",
  "The Last Legion",
  "The Last Kingdom",
  "The Last King Of Scotland",
  "The Last Duel",
  "The Last Deal",
  "The Last Days of Ptolemy Grey",
  "The Last Dance",
  "The Lars Larson Show",
  "The Larry Sanders Show",
  "The Larry Elder Show",
  "The Knick (IS WOKE!)",
  "The King's Speech",
  "The King of Kong: A Fistful of Quarters",
  "The King",
  "The Killing Fields",
  "The Killing",
  "The Kids Are Alright",
  "The Kid Detective",
  "The Kevin Roberts Show",
  "The Karate Kid",
  "The Jungle Book (2016)",
  "The Judge",
  "The Joe Rogan Experience",
  "The Joe Piscopo Show",
  "The Jetsons",
  "The Jesse Lee Peterson Radio Show",
  "The Jeffersons",
  "The Jacket",
  "The Italian Job",
  "The IT Crowd",
  "The Island",
  "The Iron Giant",
  "The Irishman",
  "THE INSTITUTE",
  "The Insider",
  "The Incredibles",
  "The Inbetweeners",
  "The Impossible",
  "The Immaculate Room (IS WOKE!)",
  "The Hyperions",
  "The Hunter",
  "The Hunted",
  "The Hunt for Red October",
  "The Hunt",
  "The House With a Clock In Its Walls",
  "The Hot Spot",
  "The Honeymooners",
  "The Homeschool Awakening",
  "The Holiday",
  "The Hitman's Bodyguard",
  "The Hitchhiker's Guide to the Galaxy",
  "The Hitcher (2007)",
  "The Hitcher (1986)",
  "The Highwaymen",
  "The Hardy Boys (2020)",
  "The Hard Way (1991)",
  "The Hangover",
  "The Guns of Navarone",
  "The Gumby Show",
  "The Guest",
  "The Gryphon (AKA: Der Greif)",
  "The Green Hornet",
  "The Greatest Reset",
  "The Greatest Lie Ever Sold",
  "The Greatest Beer Run Ever",
  "The Great Escape II: The Untold Story",
  "The Great Escape",
  "The Great Awokening Podcast",
  "The Gray Man",
  "The Grand Tour",
  "The Graduate",
  "The Goonies",
  "The Goode Family",
  "The Good, The Bad, And The Ugly",
  "The Good Nurse",
  "The Good Lie",
  "The Good Liar",
  "The Golden Child",
  "The Godfather Part III",
  "The Godfather Part II",
  "The Godfather",
  "The Glenn Beck Program",
  "The Glenn Beck Podcast",
  "The Glass Castle (2017)",
  "The Girl from Plainville",
  "The Gift",
  "The Ghost and the Darkness",
  "The Genius Of Thomas Sowell",
  "The Game Plan",
  "The Game",
  "The Fugitive",
  "The Fountain (2006)",
  "The Founder",
  "The Fly (1986)",
  "The Flintstones (1994)",
  "The Flintstones",
  "The Final",
  "The Fellowship Of The Ring",
  "The Federalist Radio Hour",
  "The Fast and the Furious",
  "The Fabelmans",
  "The Expendables",
  "The Expanse",
  "The English",
  "The End Times",
  "The Edge",
  "The Ed Bassmaster Show",
  "The Eagle",
  "The Dukes of Hazzard",
  "The Dropout",
  "The Drew Carey Show",
  "The Double",
  "The Don't Unfriend Me Show",
  "The Dirty Dozen",
  "The Dig",
  "The Devil's Advocate",
  "The Devil You Know",
  "The Departed",
  "The Dennis Prager Show",
  "The Deer Hunter",
  "The Death of Stalin",
  "The Day the Earth Stood Still",
  "The Dawn of the Planet of the Apes",
  "The Dark Knight Rises",
  "The Dark Knight",
  "The Dana Show with Dana Loesch",
  "The Dan Bongino Show",
  "The Culture Killers: The Woke Wars",
  "The Crown",
  "The Crowded Room (IS WOKE!)",
  "The Crow",
  "The Creepy Line",
  "The Cowboys",
  "The Court Jester",
  "The Count Of Monte Cristo",
  "The Conspirator",
  "The Comments Section with Brett Cooper",
  "The Cokeville Miracle",
  "The Chronicles of Narnia: The Voyage Of The Dawn Treader",
  "The Chronicles Of Narnia: The Lion, The Witch & The Wardrobe",
  "The Chronicles Of Narnia: Prince Caspian",
  "The Chosen",
  "The Charlie Kirk Show",
  "The Cellar",
  "The Case for Christ's Resurrection",
  "The Case for Christ",
  "The Candace Owens Show",
  "The Calling",
  "The Butterfly Effect",
  "The Bucket List",
  "The Buck Sexton Show",
  "The Bridge at Remagen",
  "The Bridge",
  "The Breakfast Club",
  "The Boyscast with Ryan Long",
  "The Bourne Ultimatum",
  "The Bourne Supremacy",
  "The Bourne Identity",
  "The Borgias",
  "The Boondock Saints",
  "The Book Of Eli",
  "The Bob Newhart Show",
  "The Blind Side",
  "The Blair Witch Project",
  "The Blacklist",
  "The Black Phone",
  "The Biggest Bully in School: Why Public Education Is Failing in America",
  "The Big Short",
  "The Big Lebowski",
  "The Big Green",
  "The Big Door Prize",
  "The Big Conn",
  "The Big Bang Theory",
  "The Ben Shapiro Show",
  "The Bear",
  "The Banshees of Inisherin",
  "The Ballad of Buster Scruggs",
  "The Bad Guys",
  "The Babylon Bee",
  "The Atheist Delusion",
  "The Assassination Of Jesse James By The Coward Robert Ford",
  "The Apple Dumpling Gang",
  "The Andy Griffith Show",
  "The Andrew Klavan Show",
  "The Americans",
  "The Amazing World of Gumball",
  "The Adventures of Tintin",
  "The Adam Project",
  "The Adam Carolla Show",
  "The Adam And Dr Drew Show",
  "The A Team",
  "The 300 Spartans",
  "The 15:17 To Paris",
  "The 13th Warrior",
  "That Dirty Black Bag",
  "That '90s Show (IS WOKE!)",
  "Texas Rising",
  "Tetris",
  "Terror On The Prairie",
  "Terriers",
  "Terrence K. Williams",
  "Terminator 4: Salvation (IS WOKE!)",
  "Terminator 3: Rise of the Machines",
  "Terminator 2 Judgement Day",
  "Tehran",
  "Tears Of The Sun",
  "Tall Tale - The Unbelievable Adventure of Pecos Bill",
  "TaleSpin",
  "Taken",
  "Tag",
  "Taboo",
  "Sympathy for Mr. Vengeance",
  "Swordfish",
  "Swiss Family Robinson",
  "Sweet Magnolias",
  "Swamp People",
  "Surrogates",
  "Supernatural",
  "Superbad",
  "Super Size Me",
  "Super League: The War For Football",
  "Super 8",
  "Sully",
  "Suits",
  "Succession (IS WOKE!)",
  "Stu Does America",
  "Stripes",
  "Stranger Than Fiction",
  "Storage Wars",
  "Stir of Echoes",
  "Stillwater",
  "Steve Hughes",
  "Steve Deace",
  "Step Brothers",
  "State of Play",
  "State of Control",
  "Starship Troopers",
  "Stargate: SG1",
  "Star Wars: The Phantom Menace",
  "Star Wars: The Empire Strikes Back",
  "Star Wars: Revenge of the Sith",
  "Star Wars: Return of the Jedi",
  "Star Wars: Attack of the Clones",
  "Star Wars: A New Hope",
  "Star Trek: Voyager",
  "Star Trek: The Original Series (1967)",
  "Star Trek: The Next Generation",
  "Star Trek: Lower Decks (IS WOKE!)",
  "Star Trek: Enterprise",
  "Star Trek: Deep Space Nine",
  "Star Trek (2009)",
  "Stand By Me",
  "Stand and Deliver",
  "Stalker (1979)",
  "Squid Game",
  "SpongeBob SquarePants",
  "Spies in Disguise",
  "Spider-Man: The Animated Series",
  "Spider-Man: No Way Home",
  "Speed",
  "Spartacus: Blood and Sand",
  "Spaced",
  "Spaceballs",
  "Space Jam",
  "Soylent Green",
  "Southern Comfort (1981)",
  "Sound of Freedom",
  "Sorcerer",
  "Sons of Anarchy",
  "Sonic the Hedgehog",
  "Son of Zorn",
  "Son of Rambow",
  "SOLAR",
  "So Help Me Todd (IS WOKE!)",
  "Sneaky Pete",
  "Snatch",
  "Smokey And The Bandit",
  "Smiling Friends",
  "Slumdog Millionaire",
  "Sling Blade",
  "Sleepless In Seattle",
  "Slapface",
  "Sky Captain and The World of Tomorrow",
  "Six Feet Under (IS WOKE!)",
  "SISU (2023)",
  "Sister Act",
  "Simulant",
  "Silverado",
  "Silver Linings Playbook",
  "Silo (IS WOKE!)",
  "Silk",
  "Silicon Valley",
  "Silence",
  "Signs",
  "Sidney",
  "Sick of It",
  "Sicario: Day Of The Soldado",
  "Sicario (IS WOKE!)",
  "Shut In",
  "Shrinking (IS WOKE)",
  "Shrek",
  "Shotgun Wedding",
  "Shotgun Stories",
  "Shot Caller",
  "Shooter",
  "Shine",
  "Sherlock Holmes",
  "Sherlock",
  "Shaun Of The Dead",
  "Shantaram",
  "Shanghai Noon",
  "Shanghai Knights",
  "Shane Gillis",
  "Shallow Hal",
  "Shadowlands",
  "Severance (IS WOKE!)",
  "Seventh Son",
  "Servant",
  "Serenity",
  "Self/less",
  "Selection Code",
  "Seinfeld",
  "See How They Run (2022)",
  "Secretariat",
  "Secret Headquarters",
  "Seconds",
  "Secondhand Lions",
  "SEAL Team",
  "Se7en (Seven)",
  "Scrubs",
  "Scott Pilgrim vs. the World (IS WOKE!)",
  "Scorpion",
  "Scooby-Doo Where Are You?",
  "School of Rock",
  "Schindler's List",
  "Scent of a Woman",
  "Scarface",
  "Saving Private Ryan",
  "Saving Me",
  "Sav Says",
  "Samurai Champloo",
  "Samaritan",
  "S.W.A.T.",
  "RV",
  "Rushed",
  "Rush Hour 3",
  "Rush Hour 2",
  "Rush Hour",
  "Rush",
  "Runaway Train",
  "Runaway Bride",
  "Rules of Engagement",
  "Rudy",
  "Rudolph, the Red-Nosed Reindeer",
  "Rucksack Radio",
  "Ronin",
  "Rome",
  "Rogue One: A Star Wars Story",
  "Rogue Heroes",
  "Rocky",
  "Robot Wars",
  "Robot And Frank",
  "Robocop (1987)",
  "Robin Hood: Prince of Thieves",
  "Robin Hood: Men in Tights",
  "Robin Hood (2010)",
  "Rob Schneider",
  "Rob Roy",
  "Roadkill",
  "Road House",
  "Rise of the Planet of the Apes",
  "Right Makes Might - The Lincoln - Douglas Debates",
  "Ridiculousness",
  "Ride with Norman Reedus",
  "Rick and Morty (IS WOKE!)",
  "Richard Jewell",
  "Revolution",
  "Revenge of the Nerds",
  "Revelation Road 2",
  "Revelation Road",
  "Reservoir Dogs",
  "Rescued by Ruby",
  "Rescue Dawn",
  "Requiem for a Dream",
  "Renfield",
  "Remember The Titans",
  "Religion of Green",
  "Relatable with Allie Beth Stuckey",
  "Reign of Fire",
  "Redacted with Natali & Clayton Morris",
  "Red Tails",
  "Red Rock West",
  "Red Dwarf",
  "Red Dead Redemption 2",
  "Red Dawn",
  "Red Cliff",
  "Red",
  "Reboot (IS WOKE!)",
  "reba",
  "Reasons to Believe",
  "Reaper",
  "Reacher",
  "Re-Opening",
  "Raymond & Ray",
  "Ratchet & Clank: Rift Apart",
  "Ratatouille",
  "Rango",
  "Range 15",
  "Rambo: Last Blood (V)",
  "Rambo: First Blood II",
  "Rambo III",
  "Rambo (IV)",
  "Raising Arizona",
  "Raging Bull",
  "Radio",
  "Rabbit Hole (IS WOKE!)",
  "Quigley Down Under",
  "Queen of the South",
  "Quantum of Solace",
  "Puss in Boots: The Last Wish",
  "Pushing Daisies",
  "Purple Hearts (2022)",
  "Pure Luck",
  "Pulp Fiction",
  "Psych",
  "Prisoners",
  "Prison Break",
  "Princess Mononoke",
  "Prince Of Persia: The Sands Of Time",
  "Primal Fear",
  "Primal",
  "Pretty Woman",
  "Predators",
  "Predator 2",
  "Predator",
  "PragerU",
  "Poldark",
  "Pokémon Journeys: The Series",
  "Poker Face (IS WOKE!)",
  "Poirot",
  "Point Break",
  "Planet Terror",
  "Planet Of The Apes (2001)",
  "Planet Of The Apes (1968)",
  "Planes, Trains and Automobiles",
  "Plane",
  "Plan A",
  "Pitch Black",
  "Pirates of the Caribbean: The Curse of the Black Pearl",
  "Pirates of the Caribbean: On Stranger Tides",
  "Pirates of the Caribbean: Dead Men Tell No Tales",
  "Pirates of the Caribbean: Dead Man's Chest",
  "Pirates Of The Caribbean: At World's End",
  "Pinky and the Brain",
  "Pineapple Express",
  "Pig",
  "Pieces of Her",
  "Person of Interest",
  "Perception",
  "Peep Show",
  "Pee-wee's Playhouse",
  "Pee-Wee's Big Adventure",
  "Pearl Harbor",
  "Peaky Blinders",
  "PBD (The Bet-David Show)",
  "Pawn Stars",
  "Paul T. Goldman",
  "Patton",
  "Patterns of Evidence: The Exodus",
  "Patriots Day",
  "Patriot Purge",
  "Patriot Games",
  "Patrick Melrose",
  "Patch Adams",
  "Pat Gray Unleashed",
  "Passengers",
  "Party Down",
  "Parks and Recreation",
  "Parasite (IS WOKE!)",
  "Pantheon",
  "Panama",
  "Palm Springs",
  "Paint",
  "Pacific Rim",
  "Ozark (IS WOKE!)",
  "Over the Garden Wall",
  "Outlaw King",
  "Outlander (2009)",
  "Outer Range (IS WOKE!)",
  "Osmosis Jones",
  "Orphan: First Kill",
  "Operation Mincemeat (IS WOKE!)",
  "Only the Brave",
  "One-Punch Man",
  "One Tree Hill",
  "One Flew Over the Cuckoo's Nest",
  "One Day as a Lion",
  "One Bite Pizza Reviews",
  "Once Upon a Time…in Hollywood",
  "Once Upon a Time in the West",
  "On The Line",
  "Olympus Has Fallen",
  "Oldboy (2003)",
  "Old Henry",
  "Office Space",
  "Of Mice And Men",
  "Octopussy",
  "Ocean's Twelve",
  "Ocean's Thirteen",
  "Ocean's Eleven (2001)",
  "Ocean's Eleven (1960)",
  "Oblivion",
  "Obamagate",
  "O Brother, Where Art Thou?",
  "NYPD Blue",
  "Notting Hill",
  "Norsemen",
  "Norm Macdonald Live",
  "Nobody",
  "No Safe Spaces",
  "No Country for Old Men",
  "No Agenda Show",
  "Nightflyers",
  "Nightcrawler",
  "Night Passage",
  "Night at the Museum",
  "Nick of Time",
  "Nick Mullen",
  "Nick Di Paolo",
  "Next Exit",
  "NEXT",
  "NewsRadio",
  "Newsies",
  "Nefarious",
  "NCIS (IS WOKE!)",
  "Navy Seals",
  "National Lampoon's Vacation",
  "National Lampoon's Christmas Vacation",
  "Nathan For You",
  "Narcos",
  "Napoleon Dynamite",
  "Nacho Libre",
  "Mythbusters",
  "Mystic River",
  "My Son Hunter",
  "My Name Is Earl",
  "My Fair Lady",
  "My Cousin Vinny",
  "My Best Friend's Wedding",
  "Murdoch Mysteries",
  "Murder, She Wrote",
  "Murder Mystery 2",
  "Munich",
  "Mud",
  "Mrs. Harris Goes to Paris (IS WOKE!)",
  "Mrs. Doubtfire",
  "Mr. Nobody",
  "Mr. Holland's Opus",
  "Mr. Deeds",
  "Mr. Bean",
  "Mr-Inbetween",
  "Mr Jones",
  "Mother",
  "Morning Wire",
  "Moonraker",
  "Moonfall",
  "Moone Boy",
  "Moon",
  "Monty Python's Life Of Brian",
  "Monty Python's Flying Circus",
  "Monster Hunter",
  "Monk",
  "Moneyball",
  "Moment of Contact",
  "Mob Psycho 100",
  "Mixed by Erry",
  "Mister Rogers' Neighborhood",
  "Mission: Impossible IV - Ghost Protocol",
  "Mission Unexplained",
  "Missing 411: The UFO Connection",
  "Missing",
  "Miss Peregrine's Home for Peculiar Children",
  "Miss Congeniality",
  "Miss Bala",
  "Misfits",
  "Misery",
  "Mischief",
  "Miracle On 34th Street (1994)",
  "Miracle On 34th Street (1947)",
  "Miracle (2004)",
  "Minority Report",
  "Minions: The Rise of Gru",
  "Mindhunter (IS WOKE!)",
  "Minamata",
  "Million Dollar Baby",
  "Millennium",
  "Mile 22",
  "Mike Tyson Mysteries",
  "Midway (2019)",
  "Midway (1976)",
  "Midsomer Murders",
  "Midnight Cowboy (IS WOKE!)",
  "Mickey's Christmas Carol",
  "Michael Jr.",
  "MFKZ (aka: Mutafukaz)",
  "Metro Exodus",
  "Metalocalypse",
  "Metal Lords",
  "Mending the Line",
  "Men in Black II",
  "Men In Black 3",
  "Men In Black",
  "Memphis Belle",
  "Memory",
  "Memento",
  "Melancholia",
  "Meet the Fockers",
  "Medieval",
  "Medellin",
  "Me, Myself And Irene",
  "Maverick",
  "Matt Rife",
  "Master and Commander: The Far Side of the World",
  "Mars Attacks!",
  "Married With Children",
  "Marlowe",
  "Mark Dice",
  "Margin Call",
  "Marcel the Shell with Shoes On",
  "Manifest",
  "Manhunt: UNABOMBER",
  "Manhattan",
  "Man on Wire",
  "Man on Fire",
  "Mammals",
  "Malcolm in the Middle",
  "Make My Day",
  "Major Payne",
  "Major League",
  "MacGyver (2016)",
  "M3GAN",
  "Luther",
  "Lucky Number Slevin",
  "Luck (IS WOKE!)",
  "Love, Death & Robots",
  "LOVE Actually",
  "Louis Armstrong's Black & Blues",
  "Loudermilk",
  "Louder With Crowder",
  "Lost in Space (2018)",
  "Lost In Space",
  "Lost",
  "Lore (IS WOKE!)",
  "Lord of War",
  "Lord of the Flies (1990)",
  "Lord of the Flies (1963)",
  "Looney Tunes",
  "Longmire",
  "Long Way Round",
  "Long Way Down",
  "Lonesome Dove",
  "Lone Survivor",
  "Logan’s Run (1976)",
  "Logan Lucky",
  "Lockwood & Co",
  "Locke",
  "Living With Liberty",
  "Living in Oblivion",
  "Live PD: Police Patrol",
  "Live Die Repeat Edge of Tomorrow",
  "Live And Let Die",
  "Little Shop of Horrors (1986)",
  "Little Pink House",
  "Little House on the Prairie",
  "Little Giants",
  "Little Big Man",
  "Listener Kids",
  "Linoleum",
  "Lincoln",
  "Limitless",
  "Life on the Line",
  "Life on Mars",
  "Life of Pi",
  "Life After Beth",
  "Lie to Me",
  "Licence to Kill",
  "Libs of Tik Tok",
  "Letterkenny",
  "Lethal Weapon",
  "Let Him Go",
  "Legion (IS WOKE!)",
  "Legend Of The Drunken Master",
  "Left Behind: World at War",
  "Left Behind: The Movie (2001)",
  "Left Behind: Rise of the Antichrist",
  "Left Behind (2014)",
  "Lean on Me",
  "Layer Cake",
  "Lawless",
  "Last Stand at Saber River",
  "Last of the Dogmen",
  "Last Man Standing",
  "Last Knights",
  "Last Action Hero",
  "Larry the Cable Guy",
  "Ladyhawke",
  "Lady Vengeance",
  "La Bamba",
  "L.A. Confidential",
  "Kung Fury",
  "Kong: Skull Island",
  "Klaus",
  "Kingsman: The Secret Service",
  "Kingdom of Heaven",
  "Kingdom",
  "King Richard",
  "King of the Hill",
  "King Arthur: Legend of the Sword",
  "King Arthur",
  "Kindergarten Cop",
  "Killjoys",
  "Killing Them Softly",
  "Kill The Messenger",
  "Kill Chain: The Cyber War on America's Elections",
  "Kill Bill",
  "Kid Cannabis",
  "Kickboxer",
  "Kevin Can Wait",
  "Kelly's Heroes",
  "Keeping Mum",
  "Kandahar (2023)",
  "K-VON",
  "K-PAX",
  "Juvenile Justice",
  "Justified",
  "Just Go With It",
  "Jury Duty (IS WOKE!)",
  "Jurassic Punk",
  "Jurassic Park",
  "Juno",
  "Jungle",
  "Jumanji: Welcome to the Jungle",
  "Jumanji: The Next Level",
  "Jumanji (1995)",
  "Josh Denny",
  "Jordon B. Peterson",
  "Jonny Quest",
  "Jonathan Strange & Mr Norrell",
  "Jonah: A VeggieTales Movie",
  "Joker",
  "Johnny English",
  "John Wick: Chapter 4",
  "John Wick: Chapter 3 - Parabellum",
  "John Wick: Chapter 2",
  "John Wick",
  "John Solomon Reports",
  "John Pinette",
  "John Carter",
  "John Branyan",
  "John Adams",
  "Joe Pickett",
  "Joe Frank",
  "Joe",
  "Jocko Podcast",
  "Jingle All The Way",
  "Jimmy Dore",
  "Jim Henson's Labyrinth (1986)",
  "Jim Gaffigan",
  "Jim Breuers Breuniverse",
  "Jim Breuer",
  "Jesus Revolution",
  "Jerry & Marge Go Large",
  "Jericho",
  "Jeff Foxworthy",
  "Jeff Dunham",
  "Jeff Arcuri",
  "Jeff Allen",
  "Jeeves and Wooster",
  "James Klüg",
  "Jacob's Ladder (1990)",
  "Jackie Brown",
  "Jack Ryan: Shadow Recruit",
  "iZombie",
  "It's Always Sunny in Philadelphia (IS WOKE!)",
  "It's a Wonderful Life",
  "IT (1990)",
  "ISMO",
  "Is Genesis History?",
  "Irreligious Nation",
  "INVINCIBLE (IS WOKE!)",
  "Invasion",
  "Invader ZIM",
  "Into The Wild",
  "Interstellar",
  "Inspector Morse",
  "Insomnia",
  "Inside",
  "Innerspace",
  "Ink",
  "Inglourious Basterds",
  "Indiana Jones and the Temple of Doom",
  "Indiana Jones and the Raiders of the Lost Ark",
  "Indiana Jones and the Last Crusade",
  "Indiana Jones and the Kingdom of the Crystal Skull",
  "Independence Day",
  "Incorporated",
  "Inception",
  "In Time",
  "In the Loop",
  "In the Line of Fire",
  "In the Electric Mist",
  "In the Arena: The Debates and Lectures of William Lane Craig",
  "In Good Company",
  "In Bruges",
  "iMordecai",
  "Immortals",
  "Idiocracy",
  "Identity",
  "iCarly",
  "I Used To Be Famous",
  "I Think You Should Leave - with Tim Robinson",
  "I Think We're Alone Now",
  "I See You",
  "I Love Lucy",
  "I Can Only Imagine",
  "I Came By",
  "I Am Legend",
  "Hypnotic",
  "Hustle & Flow",
  "HUSTLE",
  "HUMANITY",
  "Human Target",
  "Howl's Moving Castle",
  "How to Train Your Dragon: The Hidden World",
  "How to Train Your Dragon 2",
  "How to Train Your Dragon",
  "How To Fake A War",
  "How Jack Became Black",
  "How I Met Your Mother",
  "How I Got Into College",
  "House on Haunted Hill",
  "House Of Gucci",
  "House of Flying Daggers",
  "House II The Second Story",
  "House",
  "Hotel Rwanda",
  "Hot Shots! Part Deux",
  "Hot Shots!",
  "Hot Rod",
  "Hot Ones",
  "Hot Fuzz",
  "Hoosiers",
  "Hoops",
  "Hooper",
  "Hook",
  "Hoodwinked",
  "Honey, I Shrunk the Kids",
  "Hondo",
  "Homeward Bound: The Incredible Journey",
  "Homeland",
  "Home Improvement",
  "Home Alone 2: Lost In New York",
  "Home Alone",
  "Hombre",
  "Holes",
  "Hogwarts Legacy",
  "Hogan's Heroes",
  "Hobo with a Shotgun",
  "Hoaxed",
  "Hitler’s Circle of Evil",
  "Hitch",
  "Hit-Monkey",
  "History Seekers",
  "His Only Son",
  "Hillbilly Elegy",
  "Hillary's America: The Secret History of the Democratic Party",
  "Highlander",
  "High Plains Drifter",
  "High Desert",
  "Hiding Out",
  "Hickok",
  "Here Comes the Boom",
  "Hercules: The Legendary Journeys",
  "Hercules (2014)",
  "Henry V",
  "Hello, Jack! The Kindness Show",
  "Hello Tomorrow!",
  "Hellboy II The Golden Army",
  "Hellboy",
  "Hell's Kitchen",
  "Hell Or High Water",
  "Hell or High Water",
  "Hell On Wheels",
  "HELIX",
  "Heels",
  "Heaven's War",
  "Heaven Is For Real",
  "Heaven Can Wait",
  "Heat",
  "He-Man and the Masters Of The Universe (2002)",
  "Hawaii Five-0 (2010)",
  "Hawaii Five-0 (1969)",
  "Hatfields & McCoys",
  "Hart of Dixie",
  "Harrow (IS WOKE!)",
  "Harriet",
  "Happy!",
  "Happy Gilmore",
  "Happy Days",
  "Hannibal",
  "Hang 'Em High",
  "Hancock",
  "Hamburger Hill",
  "Halt and Catch Fire",
  "Hacksaw Ridge",
  "H2O: Just Add Water",
  "Guy Ritchie's The Covenant",
  "Gutfeld!",
  "Gung Ho",
  "Guardians of the Galaxy Vol. 3",
  "Guardians of the Galaxy Vol. 2",
  "Guardians of the Galaxy",
  "Grown Ups 2",
  "Grown Ups",
  "Groundhog Day",
  "Grosse Pointe Blank",
  "Gross Anatomy",
  "Grimm",
  "Gridiron Gang",
  "Gremlins",
  "Green Wing",
  "Grease",
  "Grave of the Fireflies",
  "Gran Torino",
  "Gotham: The Fall and Rise of New York",
  "Gotcha!",
  "GOSNELL: The Trial of America's Biggest Serial Killer",
  "Goon",
  "Goodnight Mommy",
  "Goodfellas",
  "goodboy noah",
  "Good Will Hunting",
  "Good Omens",
  "Good Night Oppy (IS WOKE!)",
  "Good",
  "Gomorrah",
  "Goliath",
  "Goldfinger",
  "Goldeneye",
  "Gods and Generals",
  "God's Not Dead",
  "God of War: Ragnarök",
  "Glory Road",
  "Glory",
  "Gloria",
  "Gladiator",
  "Girl, Interrupted",
  "Ginger Snaps",
  "Ghosts of Beirut",
  "Ghostbusters",
  "ghost writer",
  "Ghost of Tsushima",
  "Gettysburg",
  "Get the Gringo",
  "Get Smart (2008)",
  "Get Off My Lawn",
  "Genesis: Paradise Lost",
  "Genesis - The Psychological Significance of the Biblical Stories",
  "Generation Kill",
  "Gender Transformation: The Untold Realities",
  "Gattaca",
  "Gargoyles",
  "Gangs of New York",
  "Gangs of London",
  "Gamer",
  "Galaxy Quest",
  "Gabriel Iglesias",
  "G.I. Joe: The Rise of Cobra",
  "G.I. Joe: Retaliation",
  "G.I. Joe: Renegades",
  "Futurama",
  "Fury",
  "Furious 7",
  "Fuller House",
  "Full Metal Jacket",
  "Full House",
  "FUBAR (IS WOKE!)",
  "Frosty the Snowman",
  "From Russia With Love",
  "From Dusk Till Dawn",
  "From (IS WOKE!)",
  "Frog and Toad",
  "Fringe",
  "Fright Night",
  "Friends",
  "Friday Night Tights",
  "Friday Night Lights",
  "Friday Night Dinner",
  "Fresh Meat",
  "Frequently Asked Questions About Time Travel",
  "Free Solo",
  "Freaks and Geeks",
  "Freaks (2019)",
  "Frasier",
  "Frank",
  "Fractured",
  "Fourth of July",
  "Foster's Home for Imaginary Friends",
  "Fort Apache",
  "Forged in Fire",
  "Forest Gump",
  "Ford vs Ferrari",
  "Force 10 From Navarone",
  "For Your Eyes Only",
  "For a Few Dollars More",
  "Fool's Paradise",
  "Flyboys",
  "Florida Man",
  "Flight Of The Navigator",
  "Flight of the Conchords",
  "Fletch",
  "Fleccas Talks",
  "Fleabag (IS WOKE!)",
  "Flamin' Hot",
  "Fixer Upper",
  "First They Killed My Father",
  "First Knight",
  "First Blood",
  "Firewall",
  "Firefly",
  "Finding Forrester",
  "Final Fantasy XVI (IS WOKE!)",
  "Fight Club",
  "Field of Dreams",
  "Ferris Bueller's Day Off",
  "Felon",
  "Fearless with Jason Whitlock",
  "Fawlty Towers",
  "Fatman",
  "Fatima",
  "Father Ted",
  "Father Stu",
  "Father of the Bride (1991)",
  "Father Goose",
  "Fast X",
  "Fargo",
  "Family Matters",
  "Falling Down",
  "Fall",
  "Eyes Wide Shut",
  "Extraction 2020",
  "Extraction 2",
  "Extinct or Alive",
  "Explicitly Pro-Life with Kristan Hawkins",
  "Expelled: No Intelligence Allowed",
  "Expedition Unknown",
  "Exodus",
  "eXistenZ",
  "Excalibur",
  "Exam",
  "Evil",
  "Everybody Loves Raymond",
  "Every Which Way But Loose",
  "Everest",
  "Escape from Pretoria",
  "Escape From Alcatraz",
  "Ernest Saves Christmas",
  "Erin Brockovich",
  "Eraser",
  "Eragon",
  "Enter The Dragon",
  "Enigma",
  "Enemy of the State",
  "Enemy Mine",
  "Enemy At The Gates",
  "Ender's Game",
  "End of Watch",
  "Empire Records",
  "Empire of the Sun",
  "Emperor",
  "Emily the Criminal",
  "Emancipation",
  "Elvis (IS WOKE!)",
  "Eli",
  "Elf",
  "Elden Ring",
  "El Presidente",
  "El Dorado",
  "El Camino: A Breaking Bad Movie",
  "Einstein and Eddington",
  "Edward Scissorhands",
  "Edge of Tomorrow",
  "Eddie the Eagle",
  "Echo 3 (IS WOKE!)",
  "Eastbound & Down",
  "E.T. the Extra-Terrestrial",
  "Dying Light",
  "DunKirk",
  "Dune (1984)",
  "DuckTales",
  "Duck Dynasty",
  "Drugstore Cowboy",
  "Drops of God",
  "Drive",
  "Dressed To Kill",
  "Dredd",
  "Dragonheart",
  "Dragged Across Concrete",
  "Drag Me To Hell",
  "Dr. Seuss' The Grinch",
  "Dr. Seuss' How The Grinch Stole Christmas",
  "Dr. No",
  "Dr. Brain",
  "Dr Seuss' How the Grinch Stole Christmas (1966)",
  "Donnie Darko",
  "Donnie Brasco",
  "Don't F**k with Cats: Hunting an Internet Killer",
  "Doc Martin",
  "Django (1966)",
  "Disturbia",
  "District 9",
  "Disorganized Crime",
  "Disclosure (1994)",
  "Dirty Work",
  "Dirty Jobs",
  "Dirty Harry",
  "Digman!",
  "Died Suddenly",
  "Die Hard: With a Vengeance",
  "Die Hard 2 Die Harder",
  "Die Hard",
  "Die Another Day",
  "Dickie Roberts Former Child Star",
  "Diamonds Are Forever",
  "Diamond & Silk: The Podcast",
  "Dexter’s Laboratory",
  "Dexter: New Blood",
  "Dexter",
  "Devs",
  "Devotion (2022)",
  "Devil's Peak",
  "Dennis Miller",
  "Den of Thieves",
  "Demolition Man",
  "Defiance",
  "Defending the Guilty",
  "Defending Jacob",
  "Debunked. With Ben Shapiro",
  "Deathloop",
  "Death Proof",
  "Death Of A Nation",
  "Death Note",
  "Death in Paradise",
  "Deadwood",
  "Deadpool",
  "Deadliest Warrior",
  "Deadliest Catch",
  "Dead Space (2023)",
  "Dead Shot (UK Only)",
  "Dead Presidents",
  "Dead Poets Society",
  "Dead Name",
  "Dead Men Don't Wear Plaid",
  "Dead Man Walking",
  "Dead Like Me",
  "Dazed and Confused",
  "Day Shift",
  "Dawson's Creek",
  "Dave Made a Maze",
  "Dave Chappelle",
  "Das Boot",
  "Darkwing Duck",
  "Darkman",
  "Darkest Hour",
  "Dark Waters",
  "Dark To Light with Frank & Beanz",
  "Dark Matter",
  "Dark City",
  "Dark",
  "Daredevil",
  "Daniel Horowitz",
  "Dances with Wolves",
  "Dan Vs.",
  "Daisy Jones & The Six",
  "Dahmer (IS WOKE!)",
  "D3: The Mighty Ducks",
  "D2: The Mighty Ducks",
  "Cyberpunk Edgerunners",
  "Cube",
  "CS Lewis: The Most Reluctant Convert",
  "Croupier",
  "Crouching Tiger, Hidden Dragon",
  "Crossroads (1986)",
  "Crocodile Dundee",
  "Creed III",
  "Cowboy Bebop",
  "Couples Retreat",
  "Counterpart (IS WOKE!)",
  "Corner Gas",
  "Coraline",
  "Cops",
  "Cool Hand Luke",
  "Constantine",
  "Conspiracy Theory (1997)",
  "Confessions of a Dangerous Mind",
  "Conan the Destroyer",
  "Conan The Barbarian (2011)",
  "Conan The Barbarian (1982)",
  "Conagher",
  "Con Air",
  "Company of Heroes 3",
  "Community",
  "Communion",
  "Come Out Fighting",
  "Columbo",
  "Colony",
  "Collateral",
  "Cold Sweat",
  "Cold in July",
  "Cocoon",
  "Coco",
  "Cocaine Bear",
  "Coach Carter",
  "Clueless",
  "Clue",
  "Close Encounters of the Third Kind",
  "Cliffhanger",
  "Clear and Present Danger",
  "Classified",
  "Class",
  "Clash of the Titans (2010)",
  "Clash of the Titans (1981)",
  "Clarkson's Farm",
  "City Slickers",
  "City of God",
  "Citadel",
  "Circuit Breakers",
  "Cinderella Man",
  "Chuck",
  "Christmas with the Kranks",
  "Chonda Pierce",
  "Chitty Chitty Bang Bang",
  "Chisum",
  "Chip 'n' Dale Rescue Rangers",
  "Children Of Men",
  "Chicken Run",
  "Chicago P.D.",
  "Chicago Fire",
  "Chesapeake Shores",
  "Cherry",
  "Chernobyl",
  "Cheers",
  "Cheaper By The Dozen (2003)",
  "Charlie Wilson's War",
  "Charlie and the Chocolate Factory",
  "Chappelle's Show",
  "Chance",
  "Champions",
  "Centurion",
  "Cellular",
  "Celebrity Deathmatch",
  "Causeway",
  "Catch Me If You Can",
  "Castle in the Sky",
  "Cast Away",
  "Casino Royale",
  "Casino",
  "Case 63",
  "Casablanca",
  "Carter",
  "Cart Narcs",
  "Carlito's Way",
  "Captain Phillips",
  "Captain Fantastic (IS WOKE!)",
  "Captain Blood",
  "Capote",
  "Cape Fear (1991)",
  "Candace Owens Show",
  "Can't Buy Me Love",
  "Can We Take a Joke?",
  "Calvary (2014)",
  "Calls",
  "Californication",
  "Caddyshack",
  "Butch Cassidy and the Sundance Kid",
  "Burnt",
  "Burn Notice",
  "Buried",
  "Bupkis",
  "Bullitt",
  "Bullet Train (IS WOKE!)",
  "Buddy Games: Spring Awakening",
  "Buck Rogers in the 25th Century",
  "Bubba Ho-Tep",
  "Brockmire",
  "Broadchurch",
  "Brightburn",
  "Bridge To Terabithia",
  "Bridge of Spies",
  "Brian Regan",
  "Brian and Charles",
  "Brews Brothers",
  "Breaking Bad",
  "Breaking Away",
  "Breakheart Pass",
  "Breaker Morant",
  "Brazil",
  "Brawl in Cell Block 99",
  "Braveheart",
  "Brave New World",
  "Bram Stoker's Dracula",
  "Boy Meets World",
  "Bottle Rocket",
  "Boss Level",
  "Boss",
  "Bosch",
  "Bones",
  "Boardwalk Empire",
  "Bluey",
  "Blue Collar Comedy Tour The Movie",
  "Blue Bloods",
  "Blow",
  "Bloody Hell",
  "Blood Simple (1984)",
  "Blood Father",
  "Blood Diamond",
  "Blonde",
  "Blind Fury",
  "Blazing Saddles",
  "Blast from the Past",
  "Blade Runner (1982)",
  "Blade",
  "Blackhat",
  "Blackbird",
  "BlackBerry",
  "Black Rider: Revelation Road",
  "Black Hawk Down",
  "Black Books",
  "Birdy",
  "Billy the Kid",
  "Billy Madison",
  "Bill Engvall Here's Your Sign",
  "Bill Burr",
  "Big Trouble In Little China",
  "Big Jake",
  "Big George Foreman",
  "Big Fish",
  "Big Daddy",
  "Better Than Us",
  "Better Off Ted",
  "Better Call Saul",
  "Berserk",
  "Beowulf and Grendel",
  "Beowulf",
  "Bengt Washburn",
  "Ben-Hur (2016)",
  "Ben-Hur (1959)",
  "Before Sunrise",
  "Beetlejuice",
  "Beef",
  "Beavis and Butt-Head Do The Universe",
  "Beavis and Butt-Head (1993)",
  "Beau Is Afraid",
  "Beastie Boys Story",
  "Be Kind Rewind",
  "Battlestar Galactica (1978)",
  "BattleBots",
  "Battle of Britain",
  "Battle Los Angeles",
  "Batman: The Animated Series",
  "Batman Returns",
  "Batman Forever",
  "Batman Begins",
  "Batman & Robin",
  "Based on a True Story",
  "Barry",
  "Bar Rescue",
  "Banshee",
  "Bandit",
  "Band of Brothers",
  "Bad Santa 2",
  "Bad Santa",
  "Bad Lieutenant",
  "Bad Grandpa",
  "Bad Friends with Andrew Santino & Bobby Lee",
  "Back to the Future",
  "Back To School",
  "Babylon 5",
  "Babylon",
  "Baby's Day Out",
  "Awaken With JP Show",
  "AVP: Alien vs. Predator",
  "Avengement",
  "Avatar: The Last Airbender",
  "Austin Powers: International Man Of Mystery",
  "Auron MacIntyre",
  "Atypical (IS WOKE!)",
  "Attack On Titan",
  "Atlas Shrugged: Part III Who is John Galt?",
  "Atlas Shrugged: Part II",
  "Atlas Shrugged: Part I",
  "Asteroid City",
  "Ashes to Ashes",
  "Ash vs Evil Dead",
  "Arrival",
  "Arrested Development (IS WOKE!)",
  "Around The World In 80 Days (2004)",
  "Around the World in 80 Days (1956)",
  "Army of Darkness",
  "Armageddon",
  "Argo (2012)",
  "Argentina, 1985 (IS WOKE!)",
  "Archer",
  "Arcane League of Legends (IS WOKE!)",
  "Aqua Teen Hunger Force",
  "April Fool's Day",
  "Apollo 13",
  "Apocalypto",
  "Answers in Genesis Ministries",
  "Another 48 Hrs.",
  "Annie: A Royal Adventure (1995)",
  "Annie (2014)",
  "Annie (1999)",
  "Annie (1982)",
  "Anjelah Johnson",
  "Animaniacs (IS WOKE!)",
  "Animal Kingdom (2010)",
  "Animal Kingdom",
  "Animal Control",
  "Anger Management",
  "Angel and the Badman",
  "Angel",
  "Andrew Schulz",
  "Andrew Doyle",
  "An Idiot Abroad",
  "An American Werewolf in London",
  "Amistad",
  "American Underdog",
  "American Sniper",
  "American Reunion",
  "American Psycho",
  "American Made",
  "American Horror Story (IS WOKE!)",
  "American Graffiti",
  "American Experience: Henry Ford",
  "American Animals",
  "America: Imagine A World Without Her",
  "America's Forgotten Heroes",
  "Amadeus",
  "Altered Carbon",
  "Alter Ego",
  "Alphas",
  "Alone",
  "Almost Human",
  "All the Queen's Horses",
  "All Quiet On The Western Front (2022)",
  "All of Us Are Dead",
  "All in the Family",
  "All Creatures Great and Small (1978)",
  "All Creatures Great and Small",
  "Alita: Battle Angel",
  "Aliens",
  "Alien Nation",
  "Alien",
  "Alfred Hitchcock Presents",
  "Alaska Daily (IS WOKE!)",
  "Akira",
  "Airplane!",
  "Air Force One",
  "Air (2023)",
  "Agenda: Grinding America Down",
  "Agenda 2: Masters of Deceit",
  "Afterlife",
  "Adventures Of The Gummi Bears",
  "Adventure Time",
  "Adaptation.",
  "Adam Yenser",
  "Ad Astra",
  "According To Jim",
  "Absolutely Anything",
  "Absolute Power",
  "Absentia",
  "Absence of Malice",
  "About Schmidt",
  "Abolitionists Rising",
  "Abbott Elementary (IS WOKE!)",
  "A.I. Artificial Intelligence (IS WOKE!)",
  "A Young Doctor's Notebook & Other Stories",
  "A View To A Kill",
  "A Spy Among Friends (IS WOKE!)",
  "A Small Light",
  "a simple plan",
  "A Shock to the System",
  "A Scanner Darkly",
  "A Quiet Place Part II",
  "A Quiet Place",
  "A Nurse To Die For",
  "A Man Called Otto (IS WOKE!)",
  "A Knight's Tale",
  "A Hidden Life",
  "A Good Person",
  "A Fistful of Dynamite",
  "A Fistful of Dollars",
  "A Fish Called Wanda",
  "A Few Good Men",
  "A Clockwork Orange",
  "A Christmas Story Christmas",
  "A Christmas Story",
  "A Christmas Carol (1951)",
  "A Charlie Brown Thanksgiving",
  "A Charlie Brown Christmas",
  "A Bronx Tale",
  "A Bridge Too Far",
  "A Beautiful Mind",
  "5000 Blankets",
  "2016: Obama's America",
  "2000 Mules",
  "1984",
  "1923 (IS WOKE!)",
  "1917",
  "1883",
  "1408",
  "808",
  "400 Days",
  "300: Rise of an Empire",
  "300",
  "127 Hours",
  "101 Dalmatians (1996)",
  "48 Hrs.",
  "30 Days Of Night",
  "24",
  "21",
  "13 Hours: The Secret Soldiers of Benghazi",
  "13 Going On 30",
  "12 Strong",
  "12 Mighty Orphans",
  "11.22.63",
  "9",
  "8 Mile",
  "3rd Rock From The Sun",
  "3:10 to Yuma (2007)",
  "3:10 to Yuma (1957)",
  "2 Turntables and a Microphone",
];
const wiowMovies = [
  "Afghanistan",
  "Rob Schneider: Woke Up in America",
  "Nefarious",
  "What Is A Woman?",
  "Sound of Freedom",
  "Guy Ritchie’s The Covenant",
  "Big George Foreman: The Miraculous Story of the Once and Future Heavyweight Champion of the World",
  "SISU",
  "Guardians of The Galaxy Vol. 3",
  "Air",
  "Star Trek Picard (Season 3)",
  "The Pope’s Exorcist",
  "Murder Mystery 2",
  "The Passion of The Christ",
  "Tetris",
  "Jesus Revolution",
  "The Wingfeather Saga (Season 1)",
  "The Last Late Night With Steve Byrne",
  "Winnie the Pooh Blood and Honey",
  "Saving Private Ryan",
  "Everything Everywhere All At Once",
  "Shin Ultraman",
  "Elvis",
  "Violent Night",
  "Bullet Train",
  "The Terminal List (Season 1)",
  "True Romance",
  "Jean-Claude Van Johnson",
  "Once Upon A Time In Hollywood",
  "The Shining",
  "Signs",
  "A Nightmare on Elm Street",
  "Aliens",
  "Attack of The Killer Tomatoes",
  "Stardust",
  "The 40-Year-Old Virgin",
  "Teenage Mutant Ninja Turtles (1990)",
  "The Silence of The Lambs",
  "Fight Club",
  "Top Gun: Maverick",
  "American Psycho",
  "Critters",
  "Batman ’89",
  "What Dreams May Come",
  "Saving Silverman",
  "The Devil’s Advocate",
  "Scream (1996)",
  "As Good As It Gets",
  "The Shawshank Redemption",
  "Jaws",
  "Superman The Movie",
  "Indiana Jones and The Last Crusade",
  "Legend",
  "What Women Want",
  "Splash",
  "Alien",
  "Back to The Future",
  "Roxanne",
  "Nosferatu",
  "The Burbs",
  "Blast from the Past",
  "The Princess Bride",
  "Misery",
  "Galaxy Quest",
  "Somewhere In Time",
];

// const curators = { nws, wiow };

export const curatorsController = async (
  req: FastifyRequest,
  res: FastifyReply
) => {
  const curators = { nws, wiow };
  var data: Array<{
    name: string;
    alias: string;
    url: string;
    movies: Array<string>;
    totalMovies: number | null;
  }> = [];

  // for (const [key, curator] of Object.entries(curators)) {
  //   const curatorData = {
  //     name: curator.name,
  //     alias: curator.alias,
  //     url: curator.url,
  //     movies: [...curator.getShowsNames()],
  //     moviesAmount: curator.getShowsAmount(),
  //   };

  //   data.push(curatorData);
  // }

  data = [
    {
      name: "Not Woke Shows",
      alias: "nws",
      url: "https://www.notwokeshows.com/",
      movies: nwsMovies,
      totalMovies: nwsMovies.length,
    },
    {
      name: "Worth it or Woke",
      alias: "wiow",
      url: "https://www.worthitorwoke.com/",
      movies: wiowMovies,
      totalMovies: wiowMovies.length,
    },
  ];

  return data;
};
